package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SubProject_Blabla'
in the project with id = 'SubProject', and delete the patch script.
*/
create(RelativeId("SubProject"), BuildType({
    id("SubProject_Blabla")
    name = "blabla"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        script {
            scriptContent = "whoami"
        }
        script {
            scriptContent = "find ."
        }
    }
}))

